name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: RKulagin/MLTA/actions/miktex

      - name: Compile book
        run: |
          initexmf --register-root $PWD
          latexmk -pdf main.tex

      - name: Clean after build full example
        run: |
          latexmk -c ./main.tex

      - name: "Git artifact: PDF"
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            ./main.pdf